<?php
$title="What A Belbin!";
$author="Connor Jones";
$date ="September 25th, 2015";
$image="belbinhome.png";

$content_preview ="We were set the challenge of building a personality test...";

$content="We were set the challenge of building a personality test that all Academees took in our
interviews. A suggestion of something to do whilst Luke attended a meeting for no longer than 2.5 hours, actually
led into a 2.5 day project which used the collective skills of the current Academees. Obviously, Charlie was
nominated as water boy whilst everyone else cracked on with html, css, javascript, php, sequel.
<p>
I managed to get some PHP that took the inputted data from the database and set it into a multi-dimensional array
so that it would hook up with Peter's results array. I also spent some time checking each page with javascript to
make sure the database recieved a total of 10. Marta did a fab job of the HTML, lucia the sequel, peter PHP, Ross
HTML & database and Charlie produced some stylish pages in CSS.
</p><p>
There were many bugs to fix throughout but the page ran really well, with a couple of issues still lurking. It
wasn't the most user friendly website to have ever existed but from a group who has not been taught any code at
the Academy yet, I don't think they should complain... if they do, we'll just add plenty more button for them to
click :) </p>";

?>
