<?php
$title="Mayden Academy - Week 1";
$author="Connor Jones";
$date ="September 19th, 2015";
$image="macbook.jpg";

$content_preview ="Week 1 was an excellent introduction to the company...";

$content="Week 1 was an excellent introduction to the company, with a lot of software downloading to
begin with. The first complication was getting used to our new and beautiful Macs (not that I was unhappy by
this complication) but as I have only used PCs before it took a while before I got used to it.
<p>
We started learning scrum, what it means to be a scrum master and a product owner....but without
practice as that would probably be detrimental to the company.
</p><p>
Alongside scrum, we learnt git and some of its basic functions. At first this was tricky, but with practice
it has become a natural process. The only issues are when you need to push the same file to the same repository
as someone else, this can be a pain...... Get off my file!!!
</p><p>
Still happy to report that all Academees are alive and well.......... Sort of. </p>";

?>
