<?php
$title="Your children are not safe in this world.";
$author="Connor Jones";
$date ="October 2nd, 2015";
$image="olivertwist.jpg";

$content_preview ="An introduction to HTML & CSS....";

$content="An introduction to HTML & CSS. An interesting introduction, lots of new things learnt and
complications ironed out in the first week. Mike has finally introduced me to the 21st Century of combining HTML
with CSS. Tables in HTML are long gone whilst the div makes his standing in the modern world.
<p>
Efficient use of these divs is still necessary and any nesting of divs I will leave to Charlie.
The document flow is crucial to understand if you want to position anything using CSS. Float will steal your
child and dispose of it in another household if you are not careful and position: fixed; will strap it to the
highest lamp post in the neighborhood for all parents to walk past unaware of its presence.
</p><p>
If you live in the CSS world then you are beautiful on the outside, you are confident of pushing the boundaries
and being told what to do is not your forte. Unfortunately, if you want to locate your parents I suggest phoning
the Jeremy Kyle show, as there is nothing I can to do help. </p>";

?>
