<?php
$title="Scrum";
$author="Connor Jones";
$date ="October 14th, 2015";
$image="scrum.jpg";

$content_preview ="In general, scrum at Mayden does not consist of two teams trying to destroy each other...";

$content="In general, scrum at Mayden does not consist of two teams trying to destroy each other. Instead, it's a working
methodology that allows teams to collaboratively work on a project without becoming destructive to each other, productivity
and the project as a whole. The rugby scrum is still a good analogy, but instead of teams you have Mayden pushing
against the
 project.
<p>
Scrum will only work efficiently if the entire company embraces it. From the stakeholders, to the product owner, to the
scrum master and to the developers. Scrum applies at all levels individually but also requires each level to communicate
and organise together.
</p><p>
The stakeholders are the client in general. They will use the product/service and report back anything they want added,
whether there are any fixes needed to be made etc. They will make theses changes known to the company who will basically
sift out any bad ideas/changes. They will provide these new features/changes to the product owner who keeps a product
backlog of all ideas and changes required for the product. This backlog is ordered on importance of the items within it.
Making fixes will be of greatest priority in general and adding optional background colours for the user will probably be
near the bottom of the pile.
</p><p>
The product owner will provide stories for each development team. A story is a non-technical description of functionality
that needs to be inputted into the software. The story can be rejected by the team, but usually the team will take it and
split it up into tasks. These will generally stay non-technical. The team will set these new tasks onto their scrum board
so everyone knows what everyone else is working on, how their progress is getting on and whether it has been 'done' or not.
</p><p>
Scrum mastering is possibly the trickiest of all the positions as it requires someone to help the team function without
directly leading them or telling them what to do. You are there to facilitate the team, make sure Scrum is being
implemented e.g. updating the scrum board and burndown chart, making sure stand up takes place every morning etc. Scrum
can be a little confusing at time and although it is there to increase efficiency in the working environment, it can soon
get out of hand. I now timebox most things at Mayden, especially when getting toast and tea.....
</p>";

?>
