<?php
$title="We Are Not Apes";
$author="Connor Jones";
$date ="October 10th, 2015";
$image="apes.jpg";

$content_preview ="Websites are not about HTML pages my friends, we have been taken as fools for far too long...";

$content="Websites are not about HTML pages my friends, we have been taken as fools for far too long. The rise of
the academy is strong and the fall of cmd-c & cmd-v is imminent.
<p>
PHP has made its way down to the basement and is being implemented into this very website. Repetitive code is
something the academy has become accustomed to... not good. It was the move from HTML tables to css at the start
of this sprint, and now we find ourselves combining HTML & CSS with php. Only a few days ago, every link had their
own page. They were slow and unused, but now index.php is dealing with more traffic than heathrow airport.
</p>
<p>
Everything 'includes' (and there is the key word) a header and a footer from the same file. This makes it a
more efficient functioning website as the code base has been reduced significantly. It also means that I can iterate
through the blog posts and create a new blog onto my website using exactly the same code every time... useful stuff.
</p>
<p>
It all seems to be going so well, but then I have purposely tested this site on safari on my laptop. Risking life
outside of this environment just doesn't seem worth it but I may ponder on how to tackle iphones and ipads soon
as the current model isn't working how it should be... But that will be left for another time. So the apes are
rising, and next week we will make it out of the basement and takeover the meeting rooms... for two days and then
its back to the basement. I am enjoying this rise but it seems like there are still many difficulties to overcome
before we make serious advancements.
</p>";

?>
