<?php
$title="Why I Want To Code";
$author="Connor Jones";
$date ="September 17th, 2015";
$image="coding-keyboard.jpg";

$content_preview ="I've been interested in computers for as long as I can remember...";

$content="I've been interested in computers for as long as I can remember. Whenever I've experienced problems
with a computer, I've always been curious and patient in taking the time to figure out the issue, rather than
taking it out into the yard and shooting it, which is how my dad preferred to fix things! The more problems I
tried to solve, the more I learnt and the more fun I had.
<p>
The first time I ever wrote code was in a class at school. I chose to take programming lessons every Thursday
afternoon to learn very simple coding in the language, BASIC. It was something I enjoyed and I started to do
it in my free time at home as well.
</p><p>
At this point, I wasn't really thinking about coding as a potential career. It was something I enjoyed, but
didn't take it very seriously. I watched the film Social Network and found myself very eager to start learning
how to properly code so that I could build a website. I thought it was cool, and having a skill that allowed
you to create something from nothing really appealed to me. So I set to work developing my HTML knowledge and
built a website. I kept this running until the start of 2015 but got bogged down in other studies.
</p><p>
Throughout my studies I was working hard, but I was not fully enjoying my time. I was not creating anything
either. This is my motivation to learn to code: I love to create things. Coding can make an idea become reality,
it can be shared with the masses and you can tweak it until it's perfect - until it's exactly what you wanted
to make. This, I think, makes coding unique and an absolute joy to work with. I also love to think logically and
to problem solve on a day to day basis.
</p><p>
My goal in coding life is to be able to have an idea, to plan it out on paper properly and to not even have
to think about writing the code because it's become natural to me. A similar process to what I am doing right
now: typing my ideas but not having to think about the next character I type, because it just flows... </p>";

?>
