<?php
$title="Planning Prevents Piss Poor Performance";
$author="Connor Jones";
$date ="October 23rd, 2015";
$image="poor-planning.jpg";

$content_preview ="Proper Prior Planning Prevents Piss Poor Performance...";

$content="A lot of our time was spent planning, and the further into the status page project we got the more we had to
plan. This wasn't due to good organisation and planning, this was due to the fact that we were always rectifying
things from the day before. We had just had a weeks worth of scrum training that should have set us up perfectly for a
team project like this, however we didn't implement it properly. That is why I have set this post's motto as Proper Prior
Planning Prevents Piss Poor Performance.
<p>
A lack of communication from the team was definitely an error on all our parts, but the wasted time was a bigger factor.
Bringing in the time-boxing was something we tried, and keeping each other up to date with our current progress. I think
we learnt a lot from this sprint and although there were many negatives, there were also a lot of positives to take out of
it as well. Especially from the work the back-end-boyz put in. Taking the ball game from our scrum training, the first
attempt was our worst by a long way so lets hope that stays consistent and we improve from here.
</p><p>
The back-end-boyz put together some beautiful code, working the database and linking it to the front end. Trying to cut
down on our code repetition was one thing, and implementing Xtreme Programming techniques (which sounds incredible but it
must be the worst named methodology known to man) such as pair programming. This was good fun and I learnt a lot from
Charlie on the SQL front. All good stuff.
</p><p>
As we are still yet to learn php, (one of our current favourite excuses for bad code, as well as 'It's just a test
page!!') we are learning a lot of our stuff on the go and as is required. So defining a structure to our code is
difficult, but it will be good to compare our work in a couple of months time. If we are any worse, please shoot us and
put us all out of our misery. Until then, hold your fire!
</p><p>
I mentioned Xtreme Programming and you were all probably thinking of something like this:
</p><p>
<img class='post-image' src='img/extreme-programming.jpg'>
</p><p>
But nope, you couldn't be further away from the truth. It is much more like this:
</p><p>
<img class='post-image' src='img/pair-programming.jpg'>
</p><p>
I know what you are thinking... 'HA! GAAAYYYYYY!!!!!'
</p>

  ";

?>