<!DOCTYPE html>
<html>
  <head>
    <title>Connor's Blog</title>
    <link type="text/css" rel="stylesheet" media="screen" href="css/styles.css" />
      <link type="text/css" rel="stylesheet" media="screen" href="css/contact.css" />
    <link type="text/css" rel="stylesheet" media="screen" href="css/media.css" />
  </head>
  <body>

   <?php
     include 'includes/header.inc';
   ?>

   <?php
     include "pages/{$content_page}.phtml";
   ?>

   <?php
     include 'includes/footer.inc';
   ?>

  </body>
</html>
