<div id="header-bottom">
    <div class="head-left">Contact Me </div><div class="head-right">"You can tweak it until it's perfect"</div>
</div>

<div id="container">
    <div class="contact_container">
        <div class="contact"> <h2>Details</h2>
            <div class="contact_details"> <?php include "includes/contact_details.inc" ?></div>
        </div>
        <div class="contact"> <h2>Enquiry</h2>
            <div class="contact_enquiry"> <?php include "includes/contact_form.inc" ?></div>
        </div>
    </div>
</div>
