<header>
  <ul id="menu-list">
    <li><a href="index.php?page=blog">Blog Posts</a></li>
    <li><a href="index.php?page=about">About</a></li>
    <li><a href="index.php?page=blog"><img class="header-img" src="http://www.maydenacademy.co.uk//wp-content/themes/academy/uploads/2015/09/conner.png"></a></li>
    <li><a href="index.php?page=resources">Resources</a></li>
    <li><a href="index.php?page=contact">Contact</a></li>
  </ul>
  <ul id="burger-menu">
    <li id="burger"><img class="menu-img" src="img/burger-menu.png">
      <ul id="burger-list">
        <li><a href="index.php?page=blog">Blog Posts</a></li>
        <li><a href="index.php?page=about">About</a></li>
        <li><a href="index.php?page=resources">Resources</a></li>
        <li><a href="index.php?page=contact">Contact</a></li>
      </ul>
    </li>
    <li><a href="index.php?page=blog"><img class="header-img" src="http://www.maydenacademy.co.uk//wp-content/themes/academy/uploads/2015/09/conner.png"></a></li>
  </ul>
</header>
